name: Playwright Tests and SonarCloud

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test-and-scan:
    timeout-minutes: 60
    runs-on: ubuntuLatest
    steps:
      # 1. Чекаут репозитория
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Полная история для SonarCloud

      # 2. Установка Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # 3. Установка зависимостей
      - name: Install dependencies
        run: npm ci

      # 4. Установка браузеров Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5. Запуск тестов Playwright
      - name: Run Playwright tests
        run: npx playwright test

      # 6. Сохранение отчёта как артефакт
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # 7. Сканирование с SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.verbose=true
